version: '3'

services:
  irods-catalog-provider:
    container_name: irods-catalog-provider
    build:
        context: .
        dockerfile: Dockerfile.provider
    hostname: icat.example.org
    networks:
      irodsnet:
        aliases:
          - icat.example.org
    ports:
      - "1247:1247"
      #- "5432:5432"
      #- "20000-21999"

  maven:
    container_name: maven
    build:
        context: .
        dockerfile: Dockerfile.testbuild
    volumes:
      - ..:/usr/src/irods-data-repository-service
      - ./settings.xml:/root/.m2/settings.xml
    networks:
      irodsnet:
        aliases:
          - maven.example.org

networks:
   irodsnet:
    driver: bridge

     


  

  
